actions:
  pre:
    nvim-plug-install: test -e ~/.local/share/nvim/site/autoload/plug.vim || (curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim)
    nvim-plug: nvim +PlugInstall +qall
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  d_i3:
    src: config/i3
    dst: ~/.config/i3
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
    upignore:
    - "*/plugged"
    actions:
    - nvim-plug-install
    - nvim-plug
  d_zsh:
    src: config/zsh
    dst: ~/.config/zsh
    upignore:
    - "*/.zcompdump"
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
  d_polybar:
    src: config/polybar
    dst: ~/.config/polybar
profiles:
  laptop:
    dotfiles:
    - d_i3
    - d_nvim
    - d_zsh
    - f_xresources
    - d_polybar
  sjaak:
    dotfiles:
    - d_i3
    - d_nvim
    - d_zsh
    - f_xresources
    - d_polybar
